forums/urls.py
from django.urls import re_path
import forums.views as forums

app_name = 'forums'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('', forums.forums, name='forums'),
    re_path('^(?P<forum>.*\s*)/$', forums.forum, name='forum'),
    re_path('^(?P<categor>.*\s*)/(?P<forum>.*\s*)/$', forums.categor_forum, name='categor_forum'),
    re_path('strims/', forums.strims, name='strims'),
    re_path('strims_games/', forums.strims_games, name='strims_games'),
    re_path('strims_game_ganr/', forums.strims_game_ganr, name='strims_game_ganr'),
    re_path('video/', forums.video, name='video'),
    re_path('auth/', forums.auth, name='auth'),
    re_path('register/', forums.register, name='register'),
]

kursach/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('android/', mainapp.android, name='android'),
    path('ios/', mainapp.ios, name='ios'),
    path('windows_phone', mainapp.windows, name='windows_phone'),
    path('psp/', mainapp.psp, name='psp'),
    path('xbox/', mainapp.xbox, name='xbox'),
    path('login/', mainapp.user_login, name='login'),
    path('logout/', mainapp.user_logout, name='logout'),
    path('register/', mainapp.user_register, name='register'),
    re_path('^game/(?P<name>.*\s*)/$', mainapp.game, name='game'),
    re_path('^ganre/(?P<gan>.*\s*)/$', mainapp.ganre, name='ganre'),
    re_path('^(?P<os>.*\s*)/ganre/(?P<gan>.*\s*)/$', mainapp.game, name='game'),
    re_path('news/', include('news.urls', namespace='news')),
    re_path('forums/', include('forums.urls', namespace='forums')),
    re_path('^auth/', include('user.urls', namespace='auth')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import re_path
import news.views as news

app_name = 'news'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('', news.news, name='news'),
    re_path('^news/(?P<new>.*\s*)/$', news.new, name='new'),
]

user/urls.py
from django.urls import re_path
import user.views as user

app_name = 'user' # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('login/$', user.user_login, name='login'),
    re_path('logout/$', user.user_logout, name='logout'),
    re_path('register/$', user.user_register, name='register'),
    re_path('edit/$', user.user_edit, name='edit'),
    re_path('profile/(?P<id>.*\s*)/$', user.user_profile, name='profile'),
    re_path('message/$', user.user_message, name='message'),
    re_path('message/(?P<id>.*\s*)/$', user.user_message_id, name='message_id'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.db import models
from django.utils.deconstruct import deconstructible



@deconstructible
class UnicodeEmailValidator(validators.RegexValidator):
    regex = r'^[\w.]+@[\w.]+\.[a-z]+$'
    message = 'Enter a valid email. This value may contain only letters,' \
              ' numbers, and @/./+/-/_ characters.'
    flags = 0


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    email_validator = UnicodeEmailValidator()

    username = None
    email = models.EmailField(
        verbose_name='email address',
        max_length=50,
        unique=True,
        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[email_validator],
        error_messages={
            'unique': "A user with that email already exists.",
        },
    )
    first_name = models.CharField(verbose_name='Имя', max_length=15, blank=True)
    last_name = models.CharField(verbose_name='Фамилия', max_length=15, blank=True)
    avatar = models.ImageField(verbose_name='Аватарка', blank=True, default='users/ava.png', upload_to='users')
    age = models.SmallIntegerField(verbose_name='Возраст', blank=True, default=0)
    sex = models.TextField(verbose_name='Пол', blank=True)
    nickname = models.TextField(verbose_name='Никнейм', max_length=128)
    telephoneModel = models.TextField(verbose_name='Модель телефона', max_length=50)
    aboutMyself = models.TextField(verbose_name='О себе', max_length=250)
    contacts = models.TextField(verbose_name='Контакты', max_length=150)
    networksAndSites = models.TextField(verbose_name='Соцсети и сайты', max_length=100)
    favorites = models.TextField(verbose_name='Избранное', max_length=100)


class UserFriend(models.Model):
    user = models.ForeignKey(User, to_field='id', verbose_name='Пользаватель', on_delete=models.CASCADE)
    friend = models.ForeignKey(User, to_field='id', verbose_name='Друг', related_name='Друг', on_delete=models.CASCADE)

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from django.contrib.auth.models import User
import django.forms as forms
from user.models import User


class MyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class MyUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class MyUserChangeAvatarForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

user/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from user.forms import MyUserCreationForm, MyUserChangeForm
from user.models import User, UserFriend
from mainapp.models import UserGame
from django.http import JsonResponse


def user_login(request):
    # if request.is_ajax():
    #     print('AJAX login', request.META['HTTP_REFERER'])
    #     context = {
    #         'login': reverse('auth:login'),
    #     }
    #     return JsonResponse(context)
    if request.POST:
        if 'email' in request.POST and request.POST['email']:
            email = request.POST['email']
            password = request.POST['psw']
            user = authenticate(email=email, password=password)
            if user is not None:
                print('пользователь найден: ', user)
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
        elif 'fname' in request.POST and request.POST['fname']:
            first_name = request.POST['fname']
            last_name = request.POST['lname']
            request.session['fname'] = first_name
            request.session['lname'] = last_name
            return HttpResponseRedirect(reverse('auth:register'))

    return render(request, 'authapp/login.html')


def user_logout(request):
    logout(request)     # стираем токен аутентификации из cookie
    return HttpResponseRedirect(reverse('index'))


def user_register(request):
    register_form = MyUserCreationForm()
    fname = request.session.get('fname', 'Нет имени')
    lname = request.session.get('lname', 'Нет фамилии')
    if request.method == "POST":
        register_form = MyUserCreationForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            email = request.POST['email']
            password = request.POST['password1']
            user = authenticate(email=email, password=password)
            if user is not None:
                print('пользователь найден: ', user)
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        register_form = MyUserCreationForm()
    context = {
        'register_form': register_form,
        'fname': fname,
        'lname': lname,
    }

    return render(request, 'authapp/register.html', context)


def user_edit(request):
    if request.method == "POST":
        edit_form = MyUserChangeForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    else:
        edit_form = MyUserChangeForm(instance=request.user)

    context = {
        'edit_form': edit_form
    }

    return render(request, 'authapp/edit.html', context)


def user_profile(request, id=None):
    game_quantity = 0
    friend_quantity = 0
    if request.method == 'GET':
        if id:
            profile = User.objects.filter(id=id)
            profile_friend = UserFriend.objects.filter(user=id)
            profile_game = UserGame.objects.filter(user=id)
            for i in profile_game:
                game_quantity = game_quantity+1

            for u in profile_friend:
                friend_quantity = friend_quantity+1

            context = {
                'profile': profile,
                'profile_friend': profile_friend,
                'profile_game': profile_game,
                'game_quantity': game_quantity,
                'friend_quantity': friend_quantity,
            }

            return render(request, 'authapp/user_profile.html', context)

    return render(request, 'authapp/user_profile.html')


def user_message(request):
    pass


def user_message_id(request):
    pass

user/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    {% block title %}
    <title>Приложения для Андроид и iOS - GurSd.ru</title>
    {% endblock %}
    {% block css %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/user/user_profile.css">
    <link rel="stylesheet" href="/static/css/user/user.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
    {% endblock %}

</head>
<body>
{% block menu %}
<div class="menu">
    <div class="menu_user">
        <div class="user_index_site">
            <a class="{% if request.resolver_match.url_name == 'profile' %}active{% endif %}"
               href="{% url 'auth:profile' user.id %}">
                <span class="profile_gs">GS</span>
            </a>
        </div>
        <div class="index_forum_news_site">
            <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}"
               href="{% url 'index' %}">
                <span class="profile_gs_games">GSGames</span>
            </a>
            <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
               href="{% url 'forums:forums' %}">
                <span class="profile_gs_forums">GSForums</span>
            </a>
            <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
               href="{% url 'news:news' %}">
                <span class="profile_gs_news">GSNews</span>
            </a>
        </div>
        <div class="user_photo_name_btn">
            <div class="photo_name_user">
                {% if user.avatar %}
                <div class="photo_user_profile">
                    <img src="{{ user.avatar.url }}" id="user_avatar">
                </div>
                {% endif %}

                {% if user.is_authenticated %}
                <div class="name_user_profile">
                    <a href="{% url 'auth:profile' user.id %}">
                        {{user.first_name| default:"пользователь"}}
                    </a>
                </div>
                {% endif %}
            </div>
            <div class="input_output">
                {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    <svg id="login" viewBox="0 0 17.01 15.87" width="30px" height="30px" fill="red">
                        <title>выход</title>
                        <path d="M266.77 144.53a7.93 7.93 0 1 1-5.6 13.56 8.22 8.22 0 0 1-1.86-2.88h2.34a4.8 4.8 0 0 0 1 1.37 5.81 5.81 0 1 0 0-8.19 6 6 0 0 0-1.09 1.46h-2.32a7.87 7.87 0 0 1 1.89-3 8 8 0 0 1 5.6-2.34z"
                              transform="translate(-257.71 -144.53)"></path>
                        <path d="M269.54 153.15a.78.78 0 0 0 0-1.23l-2.37-2.54a1.21 1.21 0 0 0-.2-.14 1.24 1.24 0 0 0-.2-.11 1 1 0 0 0-.43-.09h-.23a1 1 0 0 0-.4.17.83.83 0 0 0-.31.31 1.34 1.34 0 0 0-.17.43.56.56 0 0 0 0 .23 1.14 1.14 0 0 0 .09.43.72.72 0 0 0 .11.2.76.76 0 0 0 .14.17l1.37 1.51-1.37 1.51a.76.76 0 0 0-.14.17 1.64 1.64 0 0 0-.11.2 1.29 1.29 0 0 0-.09.46.71.71 0 0 0 0 .23 1.21 1.21 0 0 0 .17.4.83.83 0 0 0 .31.31 1 1 0 0 0 .4.17.71.71 0 0 0 .23 0 1 1 0 0 0 .43-.09.46.46 0 0 0 .2-.11.51.51 0 0 0 .2-.14zm0-1.23z"
                              transform="translate(-257.71 -144.53)"></path>
                        <path d="M267.89 153v.62h-9.09a1.08 1.08 0 0 1-1.09-1.08 1.08 1.08 0 0 1 1.09-1.08h9.2l-.06.31c0 .14 0 .31-.06.46v.77z"
                              transform="translate(-257.71 -144.53)"></path>
                    </svg>
                </a>
                {% else %}
                <a href="{% url 'auth:login' %}">
                    <svg id="login" viewBox="0 0 17.01 15.87" width="30px" height="30px" fill="green">
                        <title>вход</title>
                        <path d="M266.77 144.53a7.93 7.93 0 1 1-5.6 13.56 8.22 8.22 0 0 1-1.86-2.88h2.34a4.8 4.8 0 0 0 1 1.37 5.81 5.81 0 1 0 0-8.19 6 6 0 0 0-1.09 1.46h-2.32a7.87 7.87 0 0 1 1.89-3 8 8 0 0 1 5.6-2.34z"
                              transform="translate(-257.71 -144.53)"></path>
                        <path d="M269.54 153.15a.78.78 0 0 0 0-1.23l-2.37-2.54a1.21 1.21 0 0 0-.2-.14 1.24 1.24 0 0 0-.2-.11 1 1 0 0 0-.43-.09h-.23a1 1 0 0 0-.4.17.83.83 0 0 0-.31.31 1.34 1.34 0 0 0-.17.43.56.56 0 0 0 0 .23 1.14 1.14 0 0 0 .09.43.72.72 0 0 0 .11.2.76.76 0 0 0 .14.17l1.37 1.51-1.37 1.51a.76.76 0 0 0-.14.17 1.64 1.64 0 0 0-.11.2 1.29 1.29 0 0 0-.09.46.71.71 0 0 0 0 .23 1.21 1.21 0 0 0 .17.4.83.83 0 0 0 .31.31 1 1 0 0 0 .4.17.71.71 0 0 0 .23 0 1 1 0 0 0 .43-.09.46.46 0 0 0 .2-.11.51.51 0 0 0 .2-.14zm0-1.23z"
                              transform="translate(-257.71 -144.53)"></path>
                        <path d="M267.89 153v.62h-9.09a1.08 1.08 0 0 1-1.09-1.08 1.08 1.08 0 0 1 1.09-1.08h9.2l-.06.31c0 .14 0 .31-.06.46v.77z"
                              transform="translate(-257.71 -144.53)"></path>
                    </svg>
                </a>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}
<div class="user_page">
    {% block content %}
    {% endblock %}
</div>

{% block js %}
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/user/script.js"></script>
{% endblock %}
</body>
</html>

user/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% block title %}
<title>GSProfile refactor</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/user/user_profile.css">
<link rel="stylesheet" href="/static/css/user/user.css">
<link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/static/css/mainapp/auth_styles.css">
{% endblock %}
{% block content %}
<div class="edit">
    <div class="edit_login-form">
        <form enctype="multipart/form-data" method="post">
            <div class="edit_info_profile">
                <span>Редактирование профиля</span>
            </div>
            <div class="edit_info_profile_border"></div>
            <div class="user_form_edit">
                <div class="f_name_input">
                    <span>Имя</span><input type="text" name="first_name" id="id_first_name" placeholder="Введите имя"
                                           value="{{user.first_name}}">
                </div>
                <div class="l_name_input">
                    <span>Фамилия</span><input type="text" name="last_name" id="id_last_name" placeholder="Введите фамилию"
                                               value="{{user.last_name}}">
                </div>
                <div class="email_input">
                    <span>Email</span><input type="text" name="email" id="id_email" placeholder="Введите email"
                                             value="{{user.email}}">
                </div>
            </div>
            <div class="btn_edit">
                <button class="btn2 edit_btn_success2"><a class="a" href="{% url 'auth:profile' user.id %}">Назад</a>
                </button>
                <button type="submit" class="btn1 edit_btn_success1">Сохранить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

user/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% block title %}
<title>GurSd</title>
{% endblock %}

{% block content %}
<div class="log-reg">
    <div class="login-form">
        <div class="enter_svg_back">
            <div class="svg_enter">
                <svg id="android" viewBox="0 0 118 118" width="35px" height="35px" fill="green">
                    <path d="M59 0a59 59 0 1 0 59 59A59 59 0 0 0 59 0zM36.2 42.4a22.2 22.2 0 0 1 6.6-15.8A22.4 22.4 0 0 1 81 42.4v17.8a3.7 3.7 0 0 1-7.4 0V42.4a14.7 14.7 0 0 0-4.4-10.5 14.9 14.9 0 0 0-10.6-4.3 15 15 0 0 0-14.9 14.9v17.8a3.7 3.7 0 0 1-7.4 0V42.4zm56.4 21.9a33.65 33.65 0 0 1-67.3 0v-10h6.3v5.9a8.3 8.3 0 0 0 2.5 5.9 8.4 8.4 0 0 0 11.8 0 8.4 8.4 0 0 0 2.5-5.9v-5.9h20.5v5.9a8.3 8.3 0 0 0 2.5 5.9 8.4 8.4 0 0 0 14.3-5.9v-5.9h7v10z">
                    </path>
                </svg>
                <span>Вход</span>
            </div>
            <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'index' %}">
                <svg width="20px" height="20px" viewBox="0 0 459 459">
                    <title>Вернуться на главную</title>
                    <path d="M178.5,140.25v-102L0,216.75l178.5,178.5V290.7c127.5,0,216.75,40.8,280.5,130.05C433.5,293.25,357,165.75,178.5,140.25z"/>
                </svg>
            </a>
        </div>
        <form method="post">
            {% csrf_token %}
            <input type="text" placeholder="Введите email" name="email" required>
            <input type="password" placeholder="Введите пароль" name="psw" required>
            <button type="submit" class="btn-success">Войти</button>
        </form>
        <div class="forgot_remember">
            <div class="remember-me"><input type="checkbox" checked="checked" name="remember">
                <span>запомнить</span>
            </div>
            <span class="forgot_password">Забыли <a href="#">пароль?</a></span>
        </div>

    </div>
    <div class="or">
        <span>ИЛИ</span>
    </div>
    <div class="register-form">
        <div class="svg_registration">
            <svg viewBox="0 0 102 102" width="35px" height="35px" fill="green">
                <title>Регистрация</title>
                <path d="M51.1 41.2a6.7 6.7 0 1 0-6.7-6.7 6.7 6.7 0 0 0 6.7 6.7z"
                      fill-rule="evenodd"></path>
                <path d="M51 0a51 51 0 1 0 51 51A51 51 0 0 0 51 0zm10.3 67.1a4.4 4.4 0 0 1 0 8.7h-4.1v2a6.3 6.3 0 1 1-12.6 0V50a16.7 16.7 0 1 1 12.6 0v17.2h4.1z"
                      fill-rule="evenodd"></path>
            </svg>
            <span>Регистрация</span>
        </div>
        <form method="post" class="register-form1">
            <input type="text" placeholder="Введите имя" name="fname" required>
            <input type="text" placeholder="Введите фамилия" name="lname" required>
            <button type="submit" class="btn-success">Далее</button>
        </form>
    </div>
</div>
</div>
{% endblock %}

user/templates/authapp/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="static/user_profile.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
</head>
<body>
<div class="user_site_message">
    <div class="message_user">
        <div class="field_friends">
            <div class="text_message">Сообщения</div>
            <div class="message_list">
                <a href="message_write.html">
                    <div class="user_hover">
                        <div class="user">
                            <div class="user_message_photo"></div>
                            <div class="user_message_name">
                                <span>Vlad</span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="field_start_message">
            <div class="create_new_message">
                <svg width="100px" height="100px" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg">
                    <style type="text/css">
                        .st0 {
                            fill: black;
                        }

                        .st1 {
                            fill: white;
                        }
                    </style>
                    <circle class="st0" cx="64" cy="64" r="64"/>
                    <path class="st1"
                          d="M100,37H28c-2.2,0-4,1.8-4,4v42c0,2.2,1.8,4,4,4h20v15.1c0,0.8,0.9,1.3,1.6,0.8L72,87h28c2.2,0,4-1.8,4-4V41  C104,38.8,102.2,37,100,37z"/>
                </svg>
            </div>
            <div class="text_for_start_message">
                <span class="can">Выберите пользователя, чтобы начать диалог</span>
            </div>
        </div>
    </div>
</div>
</body>
</html>

user/templates/authapp/message_write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="static/user_profile.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
</head>
<body>
<div class="user_site_message">
    <div class="message_user">
        <div class="field_friends">
            <div class="text_message">Сообщения</div>
            <div class="message_list">
                <a href="message_write.html">
                    <div class="user_hover">
                        <div class="user">
                            <div class="user_message_photo"></div>
                            <div class="user_message_name">
                                <span>Vlad</span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="field_enter_message">
            <div class="user_visit_online">
                <div class="user_name_photo_online">
                    <div class="online_photo_name">
                        <div class="user_online_photo"></div>
                        <div class="user_online_name">
                            <span>Vlad</span>
                        </div>
                    </div>
                    <div class="be_online">
                        <span>В сети 1ч. назад</span>
                    </div>
                </div>
            </div>
            <div class="field_show_message"></div>
        </div>
    </div>
</div>
</body>
</html>

user/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% block title %}
<title>GurSd</title>
{% endblock %}

{% block content %}
<div class="container-register">
    <div class="breadcrumbs">
        <div class="all-steps">
            <div class="arrow-step1"></div>
            <div class="step_1 trek1"><span>Шаг 1</span>
            </div>
            <div class="step_2 trek2 activestep trek"><span>Шаг 2</span>
                <!--<div class="arrow-step2"></div>-->
            </div>
            <div class="step_3 trek3 trek"><span>Шаг 3</span>

            </div>
            <div class="arrow-step3 trek"></div>
        </div>
    </div>
    <div class="user-form">
        <div class="register">
            <div class="reg-form">
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="form-step_1">
                        <input type="text" name="first_name" value="{{ fname }}" placeholder="Введите имя"
                               maxlength="30"
                               class="form-control"
                               id="id_first_name">
                        <input type="text" name="last_name" value="{{ lname }}" placeholder="Введите фамилию"
                               maxlength="150"
                               class="form-control"
                               id="id_last_name">
                        <div class="container-btn-back-step2">
                            <a class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                               href="{% url 'auth:login' %}">
                                <svg width="20px" height="20px" viewBox="0 0 459 459">
                                    <title>Назад</title>
                                    <path d="M178.5,140.25v-102L0,216.75l178.5,178.5V290.7c127.5,0,216.75,40.8,280.5,130.05C433.5,293.25,357,165.75,178.5,140.25z"/>
                                </svg>
                            </a>
                            <div class="btn btn-success btn-step-1">Далее</div>
                        </div>
                    </div>
                    <div class="form-step_2">
                        <input type="email" name="email" placeholder="Введите email" maxlength="254"
                               class="form-control"
                               id="id_email">
                        <input type="password" name="password1" placeholder="Введите пароль" class="form-control"
                               required=""
                               id="id_password1">
                        <input type="password" name="password2" placeholder="Повторите пароль"
                               class="form-control"
                               required=""
                               id="id_password2">
                        <div class="container-btn-back-step2">
                            <div class="btn-back-step1">
                                <svg width="20px" height="20px" viewBox="0 0 459 459">
                                    <title>Назад</title>
                                    <path d="M178.5,140.25v-102L0,216.75l178.5,178.5V290.7c127.5,0,216.75,40.8,280.5,130.05C433.5,293.25,357,165.75,178.5,140.25z"/>
                                </svg>
                            </div>
                            <div class="btn btn-success btn-step-2">Далее</div>
                        </div>
                    </div>
                    <div class="form-step_3">
                        <div class="img-ava">
                            <img class="users-avatar" src="" alt="">
                            <div class="download-photo">
                                <label class="input-avatar_label" for="id_avatar">
                                    <svg fill="black" width="20px" height="20px" viewBox="0 0 612.675 612.675">
                                        <path d="M581.209,223.007L269.839,530.92c-51.592,51.024-135.247,51.024-186.839,0c-51.592-51.023-51.592-133.737,0-184.761
                                            L363.248,69.04c34.402-34.009,90.15-34.009,124.553,0c34.402,34.008,34.402,89.166,0,123.174l-280.249,277.12
                                            c-17.19,17.016-45.075,17.016-62.287,0c-17.19-16.993-17.19-44.571,0-61.587L394.37,161.42l-31.144-30.793L114.144,376.975
                                            c-34.402,34.009-34.402,89.166,0,123.174c34.402,34.009,90.15,34.009,124.552,0l280.249-277.12
                                            c51.592-51.023,51.592-133.737,0-184.761c-51.593-51.023-135.247-51.023-186.839,0L36.285,330.784l1.072,1.071
                                            c-53.736,68.323-49.012,167.091,14.5,229.88c63.512,62.79,163.35,67.492,232.46,14.325l1.072,1.072l326.942-323.31
                                            L581.209,223.007z"/>
                                    </svg>
                                    <span>Выберите файл</span>
                                </label>
                                <input type="file" name="avatar" accept="image/*" value="/static/img/ava.png"
                                       id="id_avatar" class="input-avatar"
                                       onchange="showFileName()"/>
                            </div>
                        </div>
                        <div class="container-btn-back-step2">
                            <div class="btn-back-step2">
                                <svg version="1.1" id="Capa_1" x="0px" y="0px"
                                     width="20px" height="20px" viewBox="0 0 459 459"
                                     style="enable-background:new 0 0 459 459;">
                                    <title>Вернуться на главную</title>
                                    <g>
                                        <g id="reply">
                                            <path d="M178.5,140.25v-102L0,216.75l178.5,178.5V290.7c127.5,0,216.75,40.8,280.5,130.05C433.5,293.25,357,165.75,178.5,140.25z"
                                            />
                                        </g>
                                    </g>
                                </svg>
                            </div>
                            <button type="submit" class="btn2 btn-success btn-reg">Зарегистрироваться</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}